---
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    networks:
      - mqtt-network

  iot-temperature-simulator:
    build:
      context: .
    depends_on:
      - mosquitto
    ports:
      - "1884:1883"
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
