---
services:
  fake-iot:
    image: svenschmidt1502/iot-temperature-simulator:latest
    environment:
      - 'BROKER_IP=${BROKER_IP}' # CHANGE IP OF YOUR BROKER
      - 'MQTT_USERNAME=${MQTT_USERNAME}' # CHANGE USERNAME OF YOUR BROKER
      - 'MQTT_PASSWORD=${MQTT_PASSWORD}' # CHANGE PASSWORD OF YOUR BROKER
      - 'TOPIC=${TOPIC}'
    deploy:
      replicas: 1
