version: "3.8"
services:
  fake-iot:
    image: svenschmidt1502/iot-temperature-simulator:latest
    environment:
      - 'BROKER_IP=mosquittobroker.westeurope.cloudapp.azure.com' # CHANGE IP OF YOUR BROKER
    deploy:
      replicas: 10
