name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
      with:
        use: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
    - name: Build the Docker image
      run: docker buildx build -t svenschmidt1502/iot-temperature-simulator . --push
